name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y maven lsof
    - name: Check java version
      run: java -version
    - name: Build the Docker image
      run: ./gradlew build buildAuthoringTomcat -PdockerEnterprise=true
